### ISSUE TITLE
Refatorar a função AddAsync (Create Order), ela está me incomodando

### ISSUE THREAD

**Issue by DinisSimoes** [DinisSimoes/RestaurantAPI#5]

**Comment by Rian-Sm** [comment]
Sobre esta função AddAsync (Create Order) o que está incomodando exatamente?

Eu dei uma revisada no código e percebi que esta camada de serviço com este método está com uma função de tratamento de dados, coisa que o controlloler deveria gerenciar essa parte.

Outra opção para fazer o controle dos dados recebidos seriam setar os atributos do OrderDTO como "required" na entrada do controller, assim sem precisar criar métodos de validação dentro das camadas de controller e serviço.

Eu posso implementar qualquer uma das opções acima só dar o aval 🖖

**Comment by DinisSimoes** [comment]
A função está muito grande e atualmente realiza várias tarefas diferentes.
A ideia é dividir em funções auxiliares menores para aumentar o readability.

**EXEMPLO** 
private GetOrCreateCustomerAsync(costumer)
private CalculateOrderTotal(order.orderItems) 
private AddOrderItemsAsync(order.items)
 - Essa já existe na linha 101, mas atualmente adiciona apenas um item por vez. Bastaria chamá-la dentro de um loop para percorrer todos os itens do pedido.

Podes colocar os campos como required no dto por dois motivos:
 - removem-se essas funções de validação dos dados na camada de serviço
 - assim o controlador não fica muito "poluído" com validações manuais dos objetos
 
 Qualquer dúvida é só chamar 😊

**Comment by Rian-Sm** [comment]
Modifiquei o local da PR :+1:
